// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "lcmtypes/microstrain_ins_t.h"

static int __microstrain_ins_t_hash_computed;
static int64_t __microstrain_ins_t_hash;

int64_t __microstrain_ins_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __microstrain_ins_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__microstrain_ins_t_get_hash;
    (void) cp;

    int64_t hash = (int64_t)0x4453efb0a1158420LL
         + __int64_t_hash_recursive(&cp)
         + __int64_t_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __microstrain_ins_t_get_hash(void)
{
    if (!__microstrain_ins_t_hash_computed) {
        __microstrain_ins_t_hash = __microstrain_ins_t_hash_recursive(NULL);
        __microstrain_ins_t_hash_computed = 1;
    }

    return __microstrain_ins_t_hash;
}

int __microstrain_ins_t_encode_array(void *buf, int offset, int maxlen, const microstrain_ins_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].device_time), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].gyro, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].mag, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].accel, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].quat, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].pressure), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].rel_alt), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int microstrain_ins_t_encode(void *buf, int offset, int maxlen, const microstrain_ins_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __microstrain_ins_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __microstrain_ins_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __microstrain_ins_t_encoded_array_size(const microstrain_ins_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int64_t_encoded_array_size(&(p[element].utime), 1);

        size += __int64_t_encoded_array_size(&(p[element].device_time), 1);

        size += __double_encoded_array_size(p[element].gyro, 3);

        size += __double_encoded_array_size(p[element].mag, 3);

        size += __double_encoded_array_size(p[element].accel, 3);

        size += __double_encoded_array_size(p[element].quat, 4);

        size += __double_encoded_array_size(&(p[element].pressure), 1);

        size += __double_encoded_array_size(&(p[element].rel_alt), 1);

    }
    return size;
}

int microstrain_ins_t_encoded_size(const microstrain_ins_t *p)
{
    return 8 + __microstrain_ins_t_encoded_array_size(p, 1);
}

int __microstrain_ins_t_decode_array(const void *buf, int offset, int maxlen, microstrain_ins_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].device_time), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].gyro, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].mag, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].accel, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].quat, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].pressure), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].rel_alt), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __microstrain_ins_t_decode_array_cleanup(microstrain_ins_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_decode_array_cleanup(&(p[element].utime), 1);

        __int64_t_decode_array_cleanup(&(p[element].device_time), 1);

        __double_decode_array_cleanup(p[element].gyro, 3);

        __double_decode_array_cleanup(p[element].mag, 3);

        __double_decode_array_cleanup(p[element].accel, 3);

        __double_decode_array_cleanup(p[element].quat, 4);

        __double_decode_array_cleanup(&(p[element].pressure), 1);

        __double_decode_array_cleanup(&(p[element].rel_alt), 1);

    }
    return 0;
}

int microstrain_ins_t_decode(const void *buf, int offset, int maxlen, microstrain_ins_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __microstrain_ins_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __microstrain_ins_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int microstrain_ins_t_decode_cleanup(microstrain_ins_t *p)
{
    return __microstrain_ins_t_decode_array_cleanup(p, 1);
}

int __microstrain_ins_t_clone_array(const microstrain_ins_t *p, microstrain_ins_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_clone_array(&(p[element].utime), &(q[element].utime), 1);

        __int64_t_clone_array(&(p[element].device_time), &(q[element].device_time), 1);

        __double_clone_array(p[element].gyro, q[element].gyro, 3);

        __double_clone_array(p[element].mag, q[element].mag, 3);

        __double_clone_array(p[element].accel, q[element].accel, 3);

        __double_clone_array(p[element].quat, q[element].quat, 4);

        __double_clone_array(&(p[element].pressure), &(q[element].pressure), 1);

        __double_clone_array(&(p[element].rel_alt), &(q[element].rel_alt), 1);

    }
    return 0;
}

microstrain_ins_t *microstrain_ins_t_copy(const microstrain_ins_t *p)
{
    microstrain_ins_t *q = (microstrain_ins_t*) malloc(sizeof(microstrain_ins_t));
    __microstrain_ins_t_clone_array(p, q, 1);
    return q;
}

void microstrain_ins_t_destroy(microstrain_ins_t *p)
{
    __microstrain_ins_t_decode_array_cleanup(p, 1);
    free(p);
}

int microstrain_ins_t_publish(lcm_t *lc, const char *channel, const microstrain_ins_t *p)
{
      int max_data_size = microstrain_ins_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = microstrain_ins_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _microstrain_ins_t_subscription_t {
    microstrain_ins_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void microstrain_ins_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    microstrain_ins_t p;
    memset(&p, 0, sizeof(microstrain_ins_t));
    status = microstrain_ins_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding microstrain_ins_t!!!\n", status);
        return;
    }

    microstrain_ins_t_subscription_t *h = (microstrain_ins_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    microstrain_ins_t_decode_cleanup (&p);
}

microstrain_ins_t_subscription_t* microstrain_ins_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    microstrain_ins_t_handler_t f, void *userdata)
{
    microstrain_ins_t_subscription_t *n = (microstrain_ins_t_subscription_t*)
                       malloc(sizeof(microstrain_ins_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 microstrain_ins_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg microstrain_ins_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int microstrain_ins_t_subscription_set_queue_capacity (microstrain_ins_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int microstrain_ins_t_unsubscribe(lcm_t *lcm, microstrain_ins_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe microstrain_ins_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

